# Combining Datasets: Merge and Join

## Example: US States Data

In [39]:
import numpy as np
import pandas as pd

url_pop = "https://raw.githubusercontent.com/jakevdp/PythonDataScienceHandbook/refs/heads/master/notebooks_v1/data/state-population.csv"
url_areas = "https://raw.githubusercontent.com/jakevdp/PythonDataScienceHandbook/refs/heads/master/notebooks_v1/data/state-areas.csv"
url_abbrevs = "https://raw.githubusercontent.com/jakevdp/PythonDataScienceHandbook/refs/heads/master/notebooks_v1/data/state-abbrevs.csv"

pop = pd.read_csv(url_pop)
areas = pd.read_csv(url_areas)
abbrevs = pd.read_csv(url_abbrevs)

In [40]:
pop.head()

  state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0

In [41]:
areas.head()

        state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707

In [42]:
abbrevs.head()

        state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA

### Rank US states and territories by their 2010 population density

In [43]:
merged = pd.merge(pop, abbrevs, how='outer', left_on='state/region', right_on='abbreviation')
merged.head()

  state/region     ages  year  population   state abbreviation
0           AK    total  1990    553290.0  Alaska           AK
1           AK  under18  1990    177502.0  Alaska           AK
2           AK    total  1992    588736.0  Alaska           AK
3           AK  under18  1991    182180.0  Alaska           AK
4           AK  under18  1992    184878.0  Alaska           AK

In [44]:
# Remove duplicate column
merged = merged.drop('abbreviation', axis=1)
merged.head()

  state/region     ages  year  population   state
0           AK    total  1990    553290.0  Alaska
1           AK  under18  1990    177502.0  Alaska
2           AK    total  1992    588736.0  Alaska
3           AK  under18  1991    182180.0  Alaska
4           AK  under18  1992    184878.0  Alaska

In [45]:
merged.isnull().sum()

state/region     0
ages             0
year             0
population      20
state           96
dtype: int64

In [46]:
merged[merged['population'].isnull()]

     state/region     ages  year  population state
1872           PR  under18  1990         NaN   NaN
1873           PR    total  1990         NaN   NaN
1874           PR    total  1991         NaN   NaN
1875           PR  under18  1991         NaN   NaN
1876           PR    total  1993         NaN   NaN
1877           PR  under18  1993         NaN   NaN
1878           PR  under18  1992         NaN   NaN
1879           PR    total  1992         NaN   NaN
1880           PR  under18  1994         NaN   NaN
1881           PR    total  1994         NaN   NaN
1882           PR    total  1995         NaN   NaN
1883           PR  under18  1995         NaN   NaN
1884           PR  under18  1996         NaN   NaN
1885           PR    total  1996         NaN   NaN
1886           PR  under18  1998         NaN   NaN
1887           PR    total  1998         NaN   NaN
1888           PR    total  1997         NaN   NaN
1889           PR  under18  1997         NaN   NaN
1890           PR    total  1999         NaN   NaN
1891           PR  under18  1999         NaN   NaN

In [47]:
merged[merged['state'].isnull()]

     state/region     ages  year   population state
1872           PR  under18  1990          NaN   NaN
1873           PR    total  1990          NaN   NaN
1874           PR    total  1991          NaN   NaN
1875           PR  under18  1991          NaN   NaN
1876           PR    total  1993          NaN   NaN
...           ...      ...   ...          ...   ...
2203          USA    total  2010  309326295.0   NaN
2204          USA  under18  2011   73902222.0   NaN
2205          USA    total  2011  311582564.0   NaN
2206          USA  under18  2012   73708179.0   NaN
2207          USA    total  2012  313873685.0   NaN

[96 rows x 5 columns]

In [54]:
merged.loc[merged['state'].isnull(), ['state/region','state']]

     state/region state
1872           PR   NaN
1873           PR   NaN
1874           PR   NaN
1875           PR   NaN
1876           PR   NaN
...           ...   ...
2203          USA   NaN
2204          USA   NaN
2205          USA   NaN
2206          USA   NaN
2207          USA   NaN

[96 rows x 2 columns]

In [56]:
merged.loc[merged['state'].isnull(), 'state/region'].unique()

array(['PR', 'USA'], dtype=object)

In [58]:
merged.loc[merged['state/region'] == 'PR', 'state'] = 'Puerto Rico'
merged.loc[merged['state/region'] == 'USA', 'state'] = 'United States'
merged.isnull().sum()

state/region     0
ages             0
year             0
population      20
state            0
dtype: int64

In [59]:
final = pd.merge(merged, areas, on='state', how='left')
final.head()

  state/region     ages  year  population   state  area (sq. mi)
0           AK    total  1990    553290.0  Alaska       656425.0
1           AK  under18  1990    177502.0  Alaska       656425.0
2           AK    total  1992    588736.0  Alaska       656425.0
3           AK  under18  1991    182180.0  Alaska       656425.0
4           AK  under18  1992    184878.0  Alaska       656425.0

In [60]:
final.isnull().sum()

state/region      0
ages              0
year              0
population       20
state             0
area (sq. mi)    48
dtype: int64

In [67]:
final['state'][final['area (sq. mi)'].isnull()].unique()

array(['United States'], dtype=object)

In [68]:
final.dropna(inplace=True)
final.head()

  state/region     ages  year  population   state  area (sq. mi)
0           AK    total  1990    553290.0  Alaska       656425.0
1           AK  under18  1990    177502.0  Alaska       656425.0
2           AK    total  1992    588736.0  Alaska       656425.0
3           AK  under18  1991    182180.0  Alaska       656425.0
4           AK  under18  1992    184878.0  Alaska       656425.0

In [70]:
data2010 = final.query("year == 2010 & ages == 'total'")
data2010.head()

    state/region   ages  year  population       state  area (sq. mi)
43            AK  total  2010    713868.0      Alaska       656425.0
51            AL  total  2010   4785570.0     Alabama        52423.0
141           AR  total  2010   2922280.0    Arkansas        53182.0
149           AZ  total  2010   6408790.0     Arizona       114006.0
197           CA  total  2010  37333601.0  California       163707.0

In [71]:
data2010.set_index('state', inplace=True)
density = data2010['population'] / data2010['area (sq. mi)']

In [72]:
density.sort_values(ascending=False, inplace=True)
density.head()

state
District of Columbia    8898.897059
Puerto Rico             1058.665149
New Jersey              1009.253268
Rhode Island             681.339159
Connecticut              645.600649
dtype: float64

In [73]:
density.tail()

state
South Dakota    10.583512
North Dakota     9.537565
Montana          6.736171
Wyoming          5.768079
Alaska           1.087509
dtype: float64